trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: 'Build'
  displayName: 'Build simpleweb app docker image'
  jobs:
   - job: Build
     steps:
       - task: Docker@2
         inputs:
           containerRegistry: 'cicdacr'
           repository: 'simpleweb'
           command: 'buildAndPush'
           Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
           tags: |
             $(Build.BuildId)
             latest
